server:
  port: 80

token:
   token: MFUPYmRAELQO0zBlmpjm2Qx
   encodingAESKey: HB8k1sFWc5PQymiRrZdtFxukqxvRKuroJAxEYW2HiuQ
   corpID: wx3e96664c63b5f8e7
   secret: VG8HtFM3P6v8wSKiQVygGrqByNYS1zfpPjULvI_TV2-Po5McMnSuZM6aOrUrqBkh
   service:
      accessToken: https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=%s&amp;corpsecret=%s
      message: https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=%s
      mediaUpload: https://qyapi.weixin.qq.com/cgi-bin/media/upload?access_token=%s&amp;type=%s
      medaiList: https://qyapi.weixin.qq.com/cgi-bin/material/batchget?access_token=%s
